name: Build OpenSupaplex Production Release
on:
  push:
    tags:
      - v*
jobs:
  create-release:
    name: Create production release
    uses: sergiou87/open-supaplex/.github/workflows/build-release.yml@master
    with:
      version: ${{ github.ref_name }}
      prerelease: false
