name: Build OpenSupaplex Beta Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  create-release:
    name: Create release
    uses: ./.github/workflows/build-release.yml
      with:
        version: ${{ inputs.version }}
        prerelease: true
