name: Build OpenSupaplex Beta Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  create-release:
    name: Create release
    uses: sergiou87/open-supaplex/.github/workflows/build-release.yml@master
    with:
      version: ${{ inputs.version }}
      prerelease: true
